"""empty message

Revision ID: 2fe7fb3d378a
Revises: 68126ad1c807
Create Date: 2024-01-31 00:29:21.452485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe7fb3d378a'
down_revision = '68126ad1c807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('people_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
