"""empty message

Revision ID: 68126ad1c807
Revises: a5cffa318ac2
Create Date: 2024-01-29 14:32:52.491295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68126ad1c807'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.String(length=250), nullable=False),
    sa.Column('director', sa.String(length=50), nullable=False),
    sa.Column('producer', sa.String(length=100), nullable=False),
    sa.Column('realase_date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.String(length=20), nullable=False),
    sa.Column('rotation_period', sa.String(length=10), nullable=False),
    sa.Column('orbital_period', sa.String(length=10), nullable=False),
    sa.Column('gravity', sa.String(length=20), nullable=False),
    sa.Column('population', sa.String(length=20), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=False),
    sa.Column('terrain', sa.String(length=100), nullable=False),
    sa.Column('surface_water', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('starship_class', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=20), nullable=False),
    sa.Column('length', sa.String(length=10), nullable=False),
    sa.Column('crew', sa.String(length=10), nullable=False),
    sa.Column('passengers', sa.String(length=10), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=10), nullable=False),
    sa.Column('hyperdrive_rating', sa.String(length=50), nullable=False),
    sa.Column('mglt', sa.String(length=20), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=10), nullable=False),
    sa.Column('consumables', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('vehicle_class', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('length', sa.String(length=10), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=20), nullable=False),
    sa.Column('crew', sa.String(length=10), nullable=False),
    sa.Column('passengers', sa.String(length=10), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=10), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=10), nullable=False),
    sa.Column('consumables', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_starships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.String(length=10), nullable=False),
    sa.Column('eye_color', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('hair_color', sa.String(length=10), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('mass', sa.String(length=10), nullable=False),
    sa.Column('skin_color', sa.String(length=10), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('average_height', sa.String(length=10), nullable=False),
    sa.Column('average_lifespan', sa.String(length=10), nullable=False),
    sa.Column('eye_colors', sa.String(length=100), nullable=False),
    sa.Column('hair_colors', sa.String(length=100), nullable=False),
    sa.Column('skin_color', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=15), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_films',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_starships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet_people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')
        batch_op.drop_column('role_id')

    op.drop_table('planet_people')
    op.drop_table('people_vehicles')
    op.drop_table('people_starships')
    op.drop_table('people_species')
    op.drop_table('people_films')
    op.drop_table('films_species')
    op.drop_table('activity')
    op.drop_table('specie')
    op.drop_table('people')
    op.drop_table('film_vehicles')
    op.drop_table('film_starships')
    op.drop_table('film_planets')
    op.drop_table('vehicle')
    op.drop_table('starship')
    op.drop_table('role')
    op.drop_table('planet')
    op.drop_table('film')
    # ### end Alembic commands ###
