"""empty message

Revision ID: 93d51e5393f0
Revises: a903efbcd6c4
Create Date: 2024-02-01 14:28:47.726025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d51e5393f0'
down_revision = 'a903efbcd6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.drop_constraint('specie_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('specie_homeworld_id_fkey', 'planet', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###
