"""empty message

Revision ID: a903efbcd6c4
Revises: effe3992d319
Create Date: 2024-02-01 13:56:06.088146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a903efbcd6c4'
down_revision = 'effe3992d319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_homeworld_id_fkey', 'planet', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###
