"""empty message

Revision ID: effe3992d319
Revises: 45c0124cc6e4
Create Date: 2024-01-31 16:09:54.501256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effe3992d319'
down_revision = '45c0124cc6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('specie_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('specie_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
